version: "1.0"
services:
  mongodb:
    image: "mongo"
    container_name: mongo-zalo-db
    ports:
      - "27017:27017"
    volumes:
      - ./data/zalo:/data/db
    restart: always
  # nginx:
  #   image: nginx
  #   container_name: nginx-zalo
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/ssl:/etc/nginx/ssl
  #   restart: always
  redis:
    image: redis
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: always
