services:
  app:
    build:
      context: .
    container_name: zalo-backend-nodejs
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env   

  nginx:
    image: nginx
    container_name: nginx-zalo
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    restart: always

  redis:
    image: redis
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: always
