openapi: 3.0.0
info:
  title: Zalo Meta API
  version: 1.0.0
  description: API documentation for Zalo management

servers:
  - url: http://localhost:5000/api/v1
    description: Local Development Server

tags:
  - name: Users
    description: API for managing users

paths:
  /users:
    get:
      summary: Get all users
      description: Retrieve a list of all users
      tags: [Users]
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./components/user.yaml"

    post:
      summary: Create a new user
      description: Add a new user to the system
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/user.yaml"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: "./components/user.yaml"

  /users/{id}:
    get:
      summary: Get a user by ID
      description: Retrieve a single user by their ID
      tags: [Users]
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "./components/user.yaml"
        "404":
          description: User not found

    put:
      summary: Update a user
      description: Modify user information by their ID
      tags: [Users]
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./components/user.yaml"
      responses:
        "200":
          description: User updated successfully
        "404":
          description: User not found

    delete:
      summary: Delete a user
      description: Remove a user by their ID
      tags: [Users]
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user to delete
          schema:
            type: string
      responses:
        "200":
          description: User deleted successfully
        "404":
          description: User not found

components:
  schemas:
    $ref: "./components/user.yaml"
